// Complete list of all 50 CFR Titles as they appear on ecfr.gov
const ALL_CFR_TITLES = [
  {
    number: 1,
    name: "General Provisions",
    shortName: "GEN",
    agency: "General Services",
  },
  {
    number: 2,
    name: "Grants and Agreements",
    shortName: "GSA",
    agency: "General Services Administration",
  },
  {
    number: 3,
    name: "The President",
    shortName: "PRES",
    agency: "Executive Office of the President",
  },
  {
    number: 4,
    name: "Accounts",
    shortName: "ACCT",
    agency: "Government Accountability Office",
  },
  {
    number: 5,
    name: "Administrative Personnel",
    shortName: "OPM",
    agency: "Office of Personnel Management",
  },
  {
    number: 6,
    name: "Domestic Security",
    shortName: "DHS",
    agency: "Department of Homeland Security",
  },
  {
    number: 7,
    name: "Agriculture",
    shortName: "USDA",
    agency: "Department of Agriculture",
  },
  {
    number: 8,
    name: "Aliens and Nationality",
    shortName: "DHS",
    agency: "Department of Homeland Security",
  },
  {
    number: 9,
    name: "Animals and Animal Products",
    shortName: "USDA",
    agency: "Department of Agriculture",
  },
  {
    number: 10,
    name: "Energy",
    shortName: "DOE",
    agency: "Department of Energy",
  },
  {
    number: 11,
    name: "Federal Elections",
    shortName: "FEC",
    agency: "Federal Election Commission",
  },
  {
    number: 12,
    name: "Banks and Banking",
    shortName: "FDIC",
    agency: "Federal Deposit Insurance Corporation",
  },
  {
    number: 13,
    name: "Business Credit and Assistance",
    shortName: "SBA",
    agency: "Small Business Administration",
  },
  {
    number: 14,
    name: "Aeronautics and Space",
    shortName: "FAA",
    agency: "Federal Aviation Administration",
  },
  {
    number: 15,
    name: "Commerce and Foreign Trade",
    shortName: "DOC",
    agency: "Department of Commerce",
  },
  {
    number: 16,
    name: "Commercial Practices",
    shortName: "FTC",
    agency: "Federal Trade Commission",
  },
  {
    number: 17,
    name: "Commodity and Securities Exchanges",
    shortName: "SEC",
    agency: "Securities and Exchange Commission",
  },
  {
    number: 18,
    name: "Conservation of Power and Water Resources",
    shortName: "FERC",
    agency: "Federal Energy Regulatory Commission",
  },
  {
    number: 19,
    name: "Customs Duties",
    shortName: "CBP",
    agency: "Customs and Border Protection",
  },
  {
    number: 20,
    name: "Employees' Benefits",
    shortName: "DOL",
    agency: "Department of Labor",
  },
  {
    number: 21,
    name: "Food and Drugs",
    shortName: "FDA",
    agency: "Food and Drug Administration",
  },
  {
    number: 22,
    name: "Foreign Relations",
    shortName: "DOS",
    agency: "Department of State",
  },
  {
    number: 23,
    name: "Highways",
    shortName: "DOT",
    agency: "Department of Transportation",
  },
  {
    number: 24,
    name: "Housing and Urban Development",
    shortName: "HUD",
    agency: "Department of Housing and Urban Development",
  },
  {
    number: 25,
    name: "Indians",
    shortName: "BIA",
    agency: "Bureau of Indian Affairs",
  },
  {
    number: 26,
    name: "Internal Revenue",
    shortName: "IRS",
    agency: "Internal Revenue Service",
  },
  {
    number: 27,
    name: "Alcohol, Tobacco Products and Firearms",
    shortName: "ATF",
    agency: "Bureau of Alcohol, Tobacco, Firearms and Explosives",
  },
  {
    number: 28,
    name: "Judicial Administration",
    shortName: "DOJ",
    agency: "Department of Justice",
  },
  {
    number: 29,
    name: "Labor",
    shortName: "DOL",
    agency: "Department of Labor",
  },
  {
    number: 30,
    name: "Mineral Resources",
    shortName: "DOI",
    agency: "Department of the Interior",
  },
  {
    number: 31,
    name: "Money and Finance: Treasury",
    shortName: "TREAS",
    agency: "Department of the Treasury",
  },
  {
    number: 32,
    name: "National Defense",
    shortName: "DOD",
    agency: "Department of Defense",
  },
  {
    number: 33,
    name: "Navigation and Navigable Waters",
    shortName: "USCG",
    agency: "Coast Guard",
  },
  {
    number: 34,
    name: "Education",
    shortName: "ED",
    agency: "Department of Education",
  },
  {
    number: 35,
    name: "Panama Canal",
    shortName: "PC",
    agency: "Panama Canal Commission",
  },
  {
    number: 36,
    name: "Parks, Forests, and Public Property",
    shortName: "NPS",
    agency: "National Park Service",
  },
  {
    number: 37,
    name: "Patents, Trademarks, and Copyrights",
    shortName: "USPTO",
    agency: "Patent and Trademark Office",
  },
  {
    number: 38,
    name: "Pensions, Bonuses, and Veterans' Relief",
    shortName: "VA",
    agency: "Department of Veterans Affairs",
  },
  {
    number: 39,
    name: "Postal Service",
    shortName: "USPS",
    agency: "United States Postal Service",
  },
  {
    number: 40,
    name: "Protection of Environment",
    shortName: "EPA",
    agency: "Environmental Protection Agency",
  },
  {
    number: 41,
    name: "Public Contracts and Property Management",
    shortName: "GSA",
    agency: "General Services Administration",
  },
  {
    number: 42,
    name: "Public Health",
    shortName: "HHS",
    agency: "Department of Health and Human Services",
  },
  {
    number: 43,
    name: "Public Lands",
    shortName: "DOI",
    agency: "Department of the Interior",
  },
  {
    number: 44,
    name: "Emergency Management and Assistance",
    shortName: "FEMA",
    agency: "Federal Emergency Management Agency",
  },
  {
    number: 45,
    name: "Public Welfare",
    shortName: "HHS",
    agency: "Department of Health and Human Services",
  },
  {
    number: 46,
    name: "Shipping",
    shortName: "DOT",
    agency: "Department of Transportation",
  },
  {
    number: 47,
    name: "Telecommunication",
    shortName: "FCC",
    agency: "Federal Communications Commission",
  },
  {
    number: 48,
    name: "Federal Acquisition Regulations System",
    shortName: "GSA",
    agency: "General Services Administration",
  },
  {
    number: 49,
    name: "Transportation",
    shortName: "DOT",
    agency: "Department of Transportation",
  },
  {
    number: 50,
    name: "Wildlife and Fisheries",
    shortName: "FWS",
    agency: "Fish and Wildlife Service",
  },
];

module.exports = ALL_CFR_TITLES;
